x-common-env: &common-env
  TRAIN_BATCH_SIZE: "1"
  TRAIN_EPOCHS: "2"
  MODEL_NAME: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  DATA_TRAIN_END: "1000000"
  LOW_CPU_MEM_USAGE: "True"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

services:
  redis:
    image: redis:7-alpine
    container_name: fraud-detection-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fraud-detection-api
    image: fraud-detection-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:8899:8899"
    env_file:
      - .env
    environment:
      <<: *common-env
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - shared_files:/app/shared_files
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8899
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build: .
    container_name: fraud-detection-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      <<: *common-env
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - shared_files:/app/shared_files
    working_dir: /app
    command: dramatiq app.queues.job_queue --processes 8 --threads 1
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
  shared_files:
  models:
